spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/social
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    web:
      pageable:
        default-page-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace